=== awslabs/aws-media-replay-engine/source/api/controlplane/plugin/runtime/chalicelib/apischema/register_plugin.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "register_plugin",
  "type": "object",
  "definitions": {},
  "properties": {
    "Name": {
      "$id": "#/properties/Name",
      "type": "string",
      "title": "The Name Schema",
      "examples": [
        "silence-detection-ffmpeg-plugin",
        "scene-detection-rekognition-plugin"
      ],
      "pattern": "^(.*)$",
      "minLength": 3,
      "maxLength": 150
    },
    "Description": {
      "$id": "#/properties/Description",
      "type": "string",
      "title": "The Description Schema",
      "pattern": "(?s)^(.*)$",
      "minLength": 3,
      "maxLength": 250
    },
    "Class": {
      "$id": "#/properties/Class",
      "type": "string",
      "title": "The Class Schema",
      "enum": ["Classifier", "Optimizer", "Featurer", "Labeler"]
    },
    "ExecutionType": {
      "$id": "#/properties/ExecutionType",
      "type": "string",
      "title": "The ExecutionType Schema",
      "enum": ["Sync", "SyncModel"]
    },
    "SupportedMediaType": {
      "$id": "#/properties/SupportedMediaType",
      "type": "string",
      "title": "The SupportedMediaType Schema",
      "enum": ["Video", "Audio"]
    },
    "ContentGroups": {
      "$id": "#/properties/ContentGroups",
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 3,
        "maxLength": 50,
        "pattern": "^(.*)$"
      },
      "minItems": 1,
      "uniqueItems": true,
      "title": "The ContentGroups Schema",
      "examples": [["Tennis", "Soccer"]]
    },
    "ExecuteLambdaQualifiedARN": {
      "$id": "#/properties/ExecuteLambdaQualifiedARN",
      "type": "string",
      "title": "The ExecuteLambdaQualifiedARN Schema",
      "examples": [
        "arn:aws:lambda:us-east-1:123456789012:function:my-function:$LATEST",
        "arn:aws:lambda:us-east-1:123456789012:function:my-function:1"
      ],
      "pattern": "^arn:aws:lambda:([a-z]{2}-[a-z]+-\\d{1}):\\d{12}:function:[a-zA-Z0-9-_]+:(\\$LATEST|[0-9]+)"
    },
    "ModelEndpoints": {
      "$id": "#/properties/ModelEndpoints",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "$id": "#/properties/ModelEndpoints/properties/Name",
            "type": "string",
            "title": "The Name Schema",
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 150
          },
          "Version": {
            "$id": "#/properties/ModelEndpoints/properties/Version",
            "type": "string",
            "title": "The Version Schema",
            "pattern": "^(.*)$",
            "minLength": 1,
            "maxLength": 5
          }
        },
        "additionalProperties": false,
        "required": ["Name", "Version"]
      },
      "minItems": 1,
      "uniqueItems": true,
      "title": "The ModelEndpoints Schema"
    },
    "Configuration": {
      "$id": "#/properties/Configuration",
      "type": "object",
      "title": "The Configuration Schema"
    },
    "OutputAttributes": {
      "$id": "#/properties/OutputAttributes",
      "type": "object",
      "title": "The OutputAttributes Schema"
    },
    "DependentPlugins": {
      "$id": "#/properties/DependentPlugins",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^(.*)$",
        "minLength": 3,
        "maxLength": 150
      },
      "minItems": 1,
      "uniqueItems": true,
      "title": "The DependentPlugins Schema",
      "examples": [
        ["Scene-Detection-FFMPEG-Plugin", "Silence-Detection-FFMPEG-Plugin"]
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "Name",
    "Class",
    "ExecutionType",
    "SupportedMediaType",
    "ContentGroups",
    "ExecuteLambdaQualifiedARN"
  ]
}

=== awslabs/aws-media-replay-engine/tests/core/Profiles/config/DetectPassThrough100.json
{
      "Name": "TestSuite-ProfileTest-DetectPassThrough100",
      "Description": "Simple pass through detector to baseline MRE performance. With 100 output attributes.",
      "Class": "Featurer",
      "ExecutionType": "Sync",
      "SupportedMediaType": "Video",
      "ContentGroups": [
        "All"
      ],
      "ExecuteLambdaQualifiedARN": "arn:aws:lambda:AWS_REGION:AWS_ACCOUNT_ID:function:DetectPassThrough100:$LATEST",
      "OutputAttributes": {
        "Label": {
          "Description": "N/A"
        },    
        "Attribute1": {"Description": "A dummy attribute"},
        "Attribute2": {"Description": "A dummy attribute"},
        "Attribute3": {"Description": "A dummy attribute"},
        "Attribute4": {"Description": "A dummy attribute"},
        "Attribute5": {"Description": "A dummy attribute"},
        "Attribute6": {"Description": "A dummy attribute"},
        "Attribute7": {"Description": "A dummy attribute"},
        "Attribute8": {"Description": "A dummy attribute"},
        "Attribute9": {"Description": "A dummy attribute"},
        "Attribute10": {"Description": "A dummy attribute"},
        "Attribute11": {"Description": "A dummy attribute"},
        "Attribute12": {"Description": "A dummy attribute"},
        "Attribute13": {"Description": "A dummy attribute"},
        "Attribute14": {"Description": "A dummy attribute"},
        "Attribute15": {"Description": "A dummy attribute"},
        "Attribute16": {"Description": "A dummy attribute"},
        "Attribute17": {"Description": "A dummy attribute"},
        "Attribute18": {"Description": "A dummy attribute"},
        "Attribute19": {"Description": "A dummy attribute"},
        "Attribute20": {"Description": "A dummy attribute"},
        "Attribute21": {"Description": "A dummy attribute"},
        "Attribute22": {"Description": "A dummy attribute"},
        "Attribute23": {"Description": "A dummy attribute"},
        "Attribute24": {"Description": "A dummy attribute"},
        "Attribute25": {"Description": "A dummy attribute"},
        "Attribute26": {"Description": "A dummy attribute"},
        "Attribute27": {"Description": "A dummy attribute"},
        "Attribute28": {"Description": "A dummy attribute"},
        "Attribute29": {"Description": "A dummy attribute"},
        "Attribute30": {"Description": "A dummy attribute"},
        "Attribute31": {"Description": "A dummy attribute"},
        "Attribute32": {"Description": "A dummy attribute"},
        "Attribute33": {"Description": "A dummy attribute"},
        "Attribute34": {"Description": "A dummy attribute"},
        "Attribute35": {"Description": "A dummy attribute"},
        "Attribute36": {"Description": "A dummy attribute"},
        "Attribute37": {"Description": "A dummy attribute"},
        "Attribute38": {"Description": "A dummy attribute"},
        "Attribute39": {"Description": "A dummy attribute"},
        "Attribute40": {"Description": "A dummy attribute"},
        "Attribute41": {"Description": "A dummy attribute"},
        "Attribute42": {"Description": "A dummy attribute"},
        "Attribute43": {"Description": "A dummy attribute"},
        "Attribute44": {"Description": "A dummy attribute"},
        "Attribute45": {"Description": "A dummy attribute"},
        "Attribute46": {"Description": "A dummy attribute"},
        "Attribute47": {"Description": "A dummy attribute"},
        "Attribute48": {"Description": "A dummy attribute"},
        "Attribute49": {"Description": "A dummy attribute"},
        "Attribute50": {"Description": "A dummy attribute"},
        "Attribute51": {"Description": "A dummy attribute"},
        "Attribute52": {"Description": "A dummy attribute"},
        "Attribute53": {"Description": "A dummy attribute"},
        "Attribute54": {"Description": "A dummy attribute"},
        "Attribute55": {"Description": "A dummy attribute"},
        "Attribute56": {"Description": "A dummy attribute"},
        "Attribute57": {"Description": "A dummy attribute"},
        "Attribute58": {"Description": "A dummy attribute"},
        "Attribute59": {"Description": "A dummy attribute"},
        "Attribute60": {"Description": "A dummy attribute"},
        "Attribute61": {"Description": "A dummy attribute"},
        "Attribute62": {"Description": "A dummy attribute"},
        "Attribute63": {"Description": "A dummy attribute"},
        "Attribute64": {"Description": "A dummy attribute"},
        "Attribute65": {"Description": "A dummy attribute"},
        "Attribute66": {"Description": "A dummy attribute"},
        "Attribute67": {"Description": "A dummy attribute"},
        "Attribute68": {"Description": "A dummy attribute"},
        "Attribute69": {"Description": "A dummy attribute"},
        "Attribute70": {"Description": "A dummy attribute"},
        "Attribute71": {"Description": "A dummy attribute"},
        "Attribute72": {"Description": "A dummy attribute"},
        "Attribute73": {"Description": "A dummy attribute"},
        "Attribute74": {"Description": "A dummy attribute"},
        "Attribute75": {"Description": "A dummy attribute"},
        "Attribute76": {"Description": "A dummy attribute"},
        "Attribute77": {"Description": "A dummy attribute"},
        "Attribute78": {"Description": "A dummy attribute"},
        "Attribute79": {"Description": "A dummy attribute"},
        "Attribute80": {"Description": "A dummy attribute"},
        "Attribute81": {"Description": "A dummy attribute"},
        "Attribute82": {"Description": "A dummy attribute"},
        "Attribute83": {"Description": "A dummy attribute"},
        "Attribute84": {"Description": "A dummy attribute"},
        "Attribute85": {"Description": "A dummy attribute"},
        "Attribute86": {"Description": "A dummy attribute"},
        "Attribute87": {"Description": "A dummy attribute"},
        "Attribute88": {"Description": "A dummy attribute"},
        "Attribute89": {"Description": "A dummy attribute"},
        "Attribute90": {"Description": "A dummy attribute"},
        "Attribute91": {"Description": "A dummy attribute"},
        "Attribute92": {"Description": "A dummy attribute"},
        "Attribute93": {"Description": "A dummy attribute"},
        "Attribute94": {"Description": "A dummy attribute"},
        "Attribute95": {"Description": "A dummy attribute"},
        "Attribute96": {"Description": "A dummy attribute"},
        "Attribute97": {"Description": "A dummy attribute"},
        "Attribute98": {"Description": "A dummy attribute"},
        "Attribute99": {"Description": "A dummy attribute"},
        "Attribute100": {"Description": "A dummy attribute"}
      }
    }

=== awslabs/aws-media-replay-engine/tests/core/Events/config/LabelPassthrough.json
{
      "Name": "TestSuite-EventTest-LabelPassThrough",
      "Description": "A way to baseline framework latency with a trivial labeling task.",
      "Class": "Labeler",
      "ExecutionType": "Sync",
      "SupportedMediaType": "Video",
      "ContentGroups": [
        "All"
      ],
      "ExecuteLambdaQualifiedARN": "arn:aws:lambda:AWS_REGION:AWS_ACCOUNT_ID:function:LabelPassThrough:$LATEST"      
}

=== awslabs/aws-media-replay-engine/tests/core/Events/config/OptimizePassThrough.json
{
      "Name": "TestSuite-EventTest-OptimizePassThrough",
      "Description": "A way to baseline framework latency with a trivial optimization task.",
      "Class": "Optimizer",
      "ExecutionType": "Sync",
      "SupportedMediaType": "Video",
      "ContentGroups": [
        "All"
      ],
      "ExecuteLambdaQualifiedARN": "arn:aws:lambda:AWS_REGION:AWS_ACCOUNT_ID:function:OptimizePassThrough:$LATEST"
}

=== awslabs/aws-media-replay-engine/tests/core/Plugins/config/SegmentPassThrough100.json
{
      "Name": "TestSuite-ModelTest-SegmentPassThrough100",
      "Description": "This plugin is used to test MRE in a simple way by creating segments for each chunk based on time.",
      "Class": "Classifier",
      "ExecutionType": "Sync",
      "SupportedMediaType": "Video",
      "ContentGroups": [
        "All"
      ],
      "ExecuteLambdaQualifiedARN": "arn:aws:lambda:AWS_REGION:AWS_ACCOUNT_ID:function:SegmentPassThrough100:$LATEST",
      "Configuration": {
        "chunk_to_segment_ratio": "0.5"
      }
}
