=== awslabs/aws-media-replay-engine/source/api/controlplane/event/runtime/chalicelib/apischema/create_event.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "create_event",
    "type": "object",
    "definitions": {},
    "properties": {
        "Name": {
            "$id": "#/properties/Name",
            "type": "string",
            "title": "The Name Schema",
            "minLength": 3,
            "maxLength": 150,
            "pattern": "^(.*)$"
        },
        "Program": {
            "$id": "#/properties/Program",
            "type": "string",
            "title": "The Program Schema",
            "minLength": 3,
            "maxLength": 150,
            "pattern": "^(.*)$"
        },
        "Description": {
            "$id": "#/properties/Description",
            "type": "string",
            "title": "The Description Schema",
            "pattern": "(?s)^(.*)$",
            "minLength": 3,
            "maxLength": 100
        },
        "Channel": {
            "$id": "#/properties/Channel",
            "type": "string",
            "title": "The Channel Schema",
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 50
        },
        "ProgramId": {
            "$id": "#/properties/ProgramId",
            "type": "string",
            "title": "The ProgramId Schema",
            "minLength": 3,
            "maxLength": 50
        },
        "SourceVideoUrl": {
            "$id": "#/properties/SourceVideoUrl",
            "type": "string",
            "title": "The SourceVideoUrl Schema",
            "minLength": 3,
            "maxLength": 2000
        },
        "SourceVideoAuth": {
            "$id": "#/properties/SourceVideoAuth",
            "type": "object",
            "title": "The SourceVideoAuth Schema",
            "minProperties": 1
        },
        "SourceVideoMetadata": {
            "$id": "#/properties/SourceVideoMetadata",
            "type": "object",
            "title": "The SourceVideoMetadata Schema",
            "minProperties": 1
        },
        "BootstrapTimeInMinutes": {
            "$id": "#/properties/BootstrapTimeInMinutes",
            "type": "integer",
            "title": "The BootstrapTimeInMinutes Schema",
            "minimum": 0,
            "maximum": 1440
        },
        "Profile": {
            "$id": "#/properties/Profile",
            "type": "string",
            "title": "The Profile Schema",
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 150
        },
        "ContentGroup": {
            "$id": "#/properties/ContentGroup",
            "type": "string",
            "title": "The ContentGroup Schema",
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 50
        },
        "Start": {
            "$id": "#/properties/Start",
            "type": "string",
            "format": "date-time",
            "title": "The Start Schema"
        },
        "DurationMinutes": {
            "$id": "#/properties/DurationMinutes",
            "type": "integer",
            "title": "The DurationMinutes Schema",
            "minimum": 1,
            "maximum": 1440
        },
        "Archive": {
            "$id": "#/properties/Archive",
            "type": "boolean",
            "title": "The Archive Schema"
        },
        "SourceVideoBucket": {
            "$id": "#/properties/SourceVideoBucket",
            "type": "string",
            "title": "The SourceVideoBucket schema",
            "pattern": "^([a-z]+)([a-z0-9-]*)$"
        },
        "GenerateOrigClips": {
            "$id": "#/properties/GenerateOrigClips",
            "type": "boolean",
            "title": "The GenerateOrigClips Schema"
        },
        "GenerateOptoClips": {
            "$id": "#/properties/GenerateOptoClips",
            "type": "boolean",
            "title": "The GenerateOptoClips Schema"
        },
        "GenerateOrigThumbNails": {
            "$id": "#/properties/GenerateOrigThumbNails",
            "type": "boolean",
            "title": "The GenerateOrigThumbNails Schema"
        },
        "GenerateOptoThumbNails": {
            "$id": "#/properties/GenerateOptoThumbNails",
            "type": "boolean",
            "title": "The GenerateOptoThumbNails Schema"
        },
        "TimecodeSource": {
            "$id": "#/properties/TimecodeSource",
            "type": "string",
            "title": "The TimecodeSource Schema",
            "enum": ["ZERO_BASED", "UTC_BASED", "NOT_EMBEDDED"]
        },
        "StopMediaLiveChannel": {
            "$id": "#/properties/StopMediaLiveChannel",
            "type": "boolean",
            "title": "The StopMediaLiveChannel Schema"
        },
        "Variables": {
            "$id": "#/properties/Variables",
            "title": "Variables",
            "type": "object",
            "propertyNames": {
                "pattern": "^[A-Za-z][A-Za-z0-9_]{0,29}$"
              },
            "minProperties": 1,
            "additionalProperties": { "type": "string" }
        }
    },
    "additionalProperties": true,
    "oneOf": [
        {
            "required": [
                "Channel"
            ]
        },
        {
            "required": [
                "SourceVideoUrl"
            ]
        },
        {
            "required": [
                "SourceVideoBucket"
            ]
        }
    ],
    "required": [
        "Name",
        "Program",
        "Profile",
        "ContentGroup",
        "Start",
        "DurationMinutes",
        "Archive"
    ]
}

=== awslabs/aws-media-replay-engine/tests/core/Events/config/EventPassThrough.json
{
    "Name": "TS1",
    "Program": "Regression",
    "Description": "Event scheduled for Regression testing",
    "Channel": "",
    "ProgramId": "NA",
    "BootstrapTimeInMinutes": 3,
    "Profile": "",
    "ContentGroup": "All",
    "Start": "",
    "DurationMinutes": 2,
    "Archive": false,
    "GenerateOrigClips": true,
    "GenerateOptoClips": true,
    "TimecodeSource": "NOT_EMBEDDED",
    "StopMediaLiveChannel": true
}
