=== awslabs/aws-media-replay-engine/source/api/controlplane/model/runtime/chalicelib/apischema/register_model.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "register_model",
    "type": "object",
    "definitions": {},
    "properties": {
        "Name": {
            "$id": "#/properties/Name",
            "type": "string",
            "title": "The Name Schema",
            "examples": [
                "Model A - Version 1",
                "Model B - Version 2"
            ],
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 150
        },
        "Description": {
            "$id": "#/properties/Description",
            "type": "string",
            "title": "The Description Schema",
            "pattern": "(?s)^(.*)$",
            "minLength": 3,
            "maxLength": 250
        },
        "ContentGroups": {
            "$id": "#/properties/ContentGroups",
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 3,
                "maxLength": 50,
                "pattern": "^(.*)$"
            },
            "minItems": 1,
            "uniqueItems": true,
            "title": "The ContentGroups Schema",
            "examples": [
                [
                    "Tennis",
                    "Soccer"
                ]
            ]
        },
        "Endpoint": {
            "$id": "#/properties/Endpoint",
            "type": "string",
            "title": "The Endpoint Schema",
            "pattern": "^(.*)$",
            "minLength": 3,
            "maxLength": 250
        },
        "PluginClass": {
            "$id": "#/properties/PluginClass",
            "type": "string",
            "title": "The PluginClass Schema",
            "enum": ["Classifier", "Optimizer", "Featurer", "Labeler"]
        }
    },
    "additionalProperties": false,
    "required": [
        "Name",
        "ContentGroups",
        "Endpoint",
        "PluginClass"
    ]
}

=== awslabs/aws-media-replay-engine/samples/source/mre-model-samples/Models/SceneClassificationModel/config.json
{
  "Name": "SceneClassificationModel",
  "Description": "Doing contextual scene classification for frame images.It could be custom models trained from AWS AI services or from Amazon SageMaker",
  "PluginClass": "Featurer",
  "ContentGroups": [
    "All"
  ],
  "Endpoint": "arn:aws:rekognition:AWS_REGION:AWS_ACCOUNT:project/REKCL-PROJECT-NAME/version/REKCL-VERSION-NUMBER"
}
